import { useEffect, useMemo, useState } from "react";
import { FileText, PencilLine, Plus, Search } from "lucide-react";
import { createQuote, listQuotes, updateQuote } from "./api";
import type { QuoteRecord, QuoteWriteInput } from "./api";
import {
  applyQueryFilterDraft,
  createQueryFilterState,
  resetQueryFilterDraft,
  updateQueryFilterDraft,
} from "./query-filter-state.js";
import { readAppliedFilterQuery, replaceAppliedFilterQueryUrl } from "./filter-query-url.js";

const blank = (): QuoteWriteInput => ({ prospectiveStudentName: "", title: "课程计划", courseTrack: "science", startDate: new Date().toISOString().slice(0, 10), endDate: "", exchangeRate: 0.05, note: "", courses: [{ name: "日语", content: "日语", hoursPerSession: 2, weeklyFrequency: 1, unitPriceJpy: 10000 }] });
const format = (value: string | number) => Number(value).toLocaleString("zh-CN", { maximumFractionDigits: 2 });

export function QuotePage({ accessToken }: { accessToken: string }) {
  const [items, setItems] = useState<QuoteRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const initialFilterScope = () => readAppliedFilterQuery(window.location.search, ["quote"], [])?.scope ?? { values: {}, keyword: "" };
  const [queryFilters, setQueryFilters] = useState(() => createQueryFilterState(initialFilterScope())); const [notice, setNotice] = useState("");
  const [editing, setEditing] = useState<QuoteRecord | null | undefined>(undefined);
  const reload = () => { setLoading(true); listQuotes(accessToken).then(result => setItems(result.items)).catch(err => setError(err instanceof Error ? err.message : "报价读取失败")).finally(() => setLoading(false)); };
  useEffect(reload, [accessToken]);
  const visible = useMemo(() => items.filter(item => `${item.title} ${item.prospectiveStudent.name}`.toLocaleLowerCase().includes(queryFilters.applied.keyword.toLocaleLowerCase())), [items, queryFilters.applied.keyword]);
  const applyFilters = () => { const next = applyQueryFilterDraft(queryFilters); setQueryFilters(next); replaceAppliedFilterQueryUrl("quote", next.applied.values, next.applied.keyword); setNotice(""); };
  const resetFilters = () => { setQueryFilters(current => resetQueryFilterDraft(current, { values: {}, keyword: "" })); setNotice("已重置筛选条件；点击查询后刷新结果。"); };
  return <main className="flex-1 space-y-4 overflow-auto px-6 py-5 pb-16">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold">报价单</h1><p className="mt-1 text-sm text-muted-foreground">签约前独立草稿，不创建正式学生、课时或财务记录。</p></div><button className="inline-flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground" onClick={() => setEditing(null)}><Plus size={16}/>新增报价</button></div>
    <section className="rounded-lg border border-border bg-white p-4"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><input value={queryFilters.draft.keyword} onChange={event => setQueryFilters(current => updateQueryFilterDraft(current, { keyword: event.target.value }))} placeholder="搜索潜在学生或标题" className="h-9 rounded-md border border-input px-3 text-sm"/><button className="inline-flex items-center justify-center gap-1 rounded-md bg-primary px-3 text-sm text-primary-foreground" onClick={applyFilters}><Search size={15}/>查询</button><button className="rounded-md border border-border px-3 text-sm" onClick={resetFilters}>重置</button></div>{notice && <p className="mt-2 text-xs text-muted-foreground">{notice}</p>}</section>
    <div className="grid gap-3 md:grid-cols-3"><Metric label="报价草稿" value={items.filter(item => item.status === "draft").length}/><Metric label="当前查询" value={visible.length}/><Metric label="报价参考合计" value={`JPY ${format(visible.reduce((sum, item) => sum + item.totalJpy, 0))}`}/></div>
    <section className="rounded-lg border border-border bg-white"><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">报价草稿记录</h2></div>{loading ? <p className="p-8 text-center text-sm text-muted-foreground">正在读取真实报价草稿…</p> : error ? <p className="p-8 text-center text-sm text-rose-600">{error}</p> : visible.length ? <div className="divide-y divide-border">{visible.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-medium">{item.prospectiveStudent.name} · {item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.startDate.slice(0, 10)} 至 {item.endDate.slice(0, 10)} · {item.courseTrack === "science" ? "理科" : "文科"} · {item.courses.map(course => course.name).join(" / ")}</p></div><div className="flex items-center gap-3"><div className="text-right text-sm"><p className="font-medium">JPY {format(item.totalJpy)}</p><p className="text-xs text-muted-foreground">CNY 参考 {format(item.totalCny)}</p></div><button className="inline-flex items-center gap-1 rounded-md border border-border px-3 py-2 text-sm" onClick={() => setEditing(item)}><PencilLine size={15}/>编辑</button></div></div>)}</div> : <p className="p-8 text-center text-sm text-muted-foreground">暂无符合条件的报价草稿</p>}</section>
    {editing !== undefined && <QuoteModal quote={editing} accessToken={accessToken} onClose={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); reload(); setNotice("报价草稿已保存。"); }}/>} 
  </main>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg border border-border bg-white p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>; }
function QuoteModal({ quote, accessToken, onClose, onSaved }: { quote: QuoteRecord | null; accessToken: string; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<QuoteWriteInput>(() => quote ? { prospectiveStudentName: quote.prospectiveStudent.name, prospectiveStudentMemo: quote.prospectiveStudent.memo, title: quote.title, courseTrack: quote.courseTrack as "science" | "humanities", startDate: quote.startDate.slice(0, 10), endDate: quote.endDate.slice(0, 10), exchangeRate: Number(quote.exchangeRate), note: quote.note, courses: quote.courses.map(course => ({ name: course.name, content: course.content, hoursPerSession: Number(course.hoursPerSession), weeklyFrequency: course.weeklyFrequency, unitPriceJpy: course.unitPriceJpy })) } : blank()); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = <K extends keyof QuoteWriteInput>(key: K, value: QuoteWriteInput[K]) => setForm(current => ({ ...current, [key]: value }));
  const save = async () => { setSaving(true); setError(""); try { quote ? await updateQuote(accessToken, quote.id, form) : await createQuote(accessToken, form); onSaved(); } catch (err) { setError(err instanceof Error ? err.message : "保存失败"); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-lg bg-white p-5 shadow-xl"><div className="flex items-center gap-2"><FileText size={18}/><h2 className="font-semibold">{quote ? "编辑报价草稿" : "新增报价草稿"}</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label="潜在学生姓名" value={form.prospectiveStudentName} onChange={value => update("prospectiveStudentName", value)}/><Field label="文件标题" value={form.title ?? ""} onChange={value => update("title", value)}/><Field label="开始日期" type="date" value={form.startDate} onChange={value => update("startDate", value)}/><Field label="结束日期" type="date" value={form.endDate} onChange={value => update("endDate", value)}/><Field label="内部汇率 (1 JPY = CNY)" type="number" value={String(form.exchangeRate)} onChange={value => update("exchangeRate", Number(value))}/><select value={form.courseTrack} onChange={event => update("courseTrack", event.target.value as "science" | "humanities")} className="h-10 rounded-md border border-input px-3 text-sm"><option value="science">理科</option><option value="humanities">文科</option></select></div><div className="mt-5 space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">课程目录</h3><button className="text-sm text-primary" onClick={() => update("courses", [...form.courses, { name: "", content: "", hoursPerSession: 2, weeklyFrequency: 1, unitPriceJpy: 10000 }])}>新增课程</button></div>{form.courses.map((course, index) => <div key={index} className="grid gap-2 rounded-md border border-border p-3 md:grid-cols-5"><Field label="课程" value={course.name} onChange={value => update("courses", form.courses.map((item, i) => i === index ? { ...item, name: value } : item))}/><Field label="内容" value={course.content ?? ""} onChange={value => update("courses", form.courses.map((item, i) => i === index ? { ...item, content: value } : item))}/><Field label="每次 H" type="number" value={String(course.hoursPerSession)} onChange={value => update("courses", form.courses.map((item, i) => i === index ? { ...item, hoursPerSession: Number(value) } : item))}/><Field label="每周次数" type="number" value={String(course.weeklyFrequency)} onChange={value => update("courses", form.courses.map((item, i) => i === index ? { ...item, weeklyFrequency: Number(value) } : item))}/><Field label="JPY/H" type="number" value={String(course.unitPriceJpy)} onChange={value => update("courses", form.courses.map((item, i) => i === index ? { ...item, unitPriceJpy: Number(value) } : item))}/></div>)}</div>{error && <p className="mt-3 text-sm text-rose-600">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button className="rounded-md border border-border px-3 py-2 text-sm" onClick={onClose}>取消</button><button disabled={saving} className="rounded-md bg-primary px-3 py-2 text-sm text-primary-foreground" onClick={save}>{saving ? "保存中…" : "保存草稿"}</button></div></div></div>;
}
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="grid gap-1 text-xs text-muted-foreground"><span>{label}</span><input type={type} value={value} onChange={event => onChange(event.target.value)} className="h-10 rounded-md border border-input px-3 text-sm text-foreground"/></label>; }
